#!/bin/sh

echo "Creating venv"
python3 -m venv venv

echo "Sourcing venv"
source venv/bin/activate

echo "Installing pipenv"
pip install pipenv

echo "Syncing with Pipfile"
pipenv sync

echo "Setting permissions"
chmod -R g+rw /app/venv

echo "Starting server"
python3 waitress_server.py -h
